import hudson.FilePath; 
import jenkins.model.Jenkins; 
node{ 
stage('Clone repository') { 
git branch: 'main', credentialsId: 'git', url: 'https://github.com/renuka-sonar/sonar-rnd.git' 
}
stage('SonarQube Analysis') 
{ 
def scannerHome = tool 'sonarscanner'; withSonarQubeEnv() { sh "${scannerHome}/bin/sonar-scanner" } } 

